  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./volumes/jellyseerr/config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped